default:
  image: registry.gitlab.com/pages/hugo/hugo_extended:0.101.0

variables:
  HUGO_ENV: production

stages:
  - build
  - deploy

.hugo:
  script:
    - |
      cd content/divers/projet_jeu
      tar czvf resources.tar.gz resources/sprites
      cd $CI_PROJECT_DIR
    - hugo

build:
  extends: .hugo
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  extends: .hugo
  stage: deploy
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
