default:
  image: registry.gitlab.com/pages/hugo/hugo_extended:0.109.0

variables:
  HUGO_ENV: production

stages:
  - build
  - deploy

.hugo:
  before_script:
    - apk add yarn bash
  script:
    - yarn install
    - yarn build
    - hugo

build:
  extends: .hugo
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  variables:
      GIT_SUBMODULE_STRATEGY: recursive

pages:
  extends: .hugo
  stage: deploy
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
