default:
  image: registry.gitlab.com/pages/hugo/hugo_extended:0.112.5

variables:
  HUGO_ENV: production

stages:
  - build
  - deploy

.hugo:
  before_script:
    - apk add yarn bash zip
  script:
    - ./build.sh
    - hugo
  variables:
      GIT_SUBMODULE_STRATEGY: recursive

build:
  extends: .hugo
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  extends: .hugo
  stage: deploy
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
