baseURL = "https://tp.girlscancode.fr"
languageCode = "fr-fr"
title = "TPs GCC!"
theme = "gcc"

[Menu]
[[Menu.header]]
    Name = "Micropython"
    URL = "/micropython"

[[Menu.header]]
    Name = "Divers"
    URL = "/divers"
[[Menu.header]]
    Name = "Documentation"
    URL = "/documentation"
