baseURL = "https://tp.girlscancode.fr"
languageCode = "fr-fr"
title = "TPs GCC!"
theme = "prolotheme"

[params]
    logo = "gcc.svg"
    favicon = "favicon.svg"
    logoText = "Girls Can Code!'s logo"

[params.style]
  primaryColor = "#212730"
  secondaryColor = "#00afd4"
  colorScheme = ["#e6006c", "#a7c80e", "#00afd4"]
  hideTags = false

# Table of content level
[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1
  [markup.highlight]
    lineNos = true

[markup.goldmark.renderer]
unsafe = true
