baseURL = "https://tp.girlscancode.fr"
languageCode = "fr-fr"
title = "TPs GCC!"
theme = "gcc"

[params.style]
  primaryColor = "#212730"
  secondaryColor = "#00afd4"
  colorScheme = ["#e6006c", "#a7c80e", "#00afd4"]
  menuOffset = 10

# Table of content level
[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1
  [markup.highlight]
    lineNos = true

[markup.goldmark.renderer]
unsafe = true


# Here are the header menus
[Menu]
[[Menu.header]]
    Name = "Micropython"
    URL = "/micropython"
    weight = 1

[[Menu.header]]
    Name = "Python et autre"
    URL = "/divers"
    weight = 5

# not yet used
#[[Menu.header]]
#    Name = "Documentation"
#    URL = "/documentation"
#    weight = 10

